# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17053174e3cd18df880e1ed0c26952f585f16889b809c9d95eab00fd800aa5e78ffc2bee1c8344344f1fa00315dd9f6ab7b603ff436e9c04023ab4a2a0a69c27

test:
  secret_key_base: 5fae56de3f2693408b9cf1578a935f7dcf78949d7c0a8f17e0c7a6e42f8a03a59c1b69ad8b193add64b3532878215bae3c0ad523f53933099a50884cac855176

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
